{
 "title": "Online Store Point of Sales",
 "time": { "from": "2023-03-08T19:02:03.000Z", "to": "2023-03-08T22:24:29.000Z" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": {
    "content": "<center>\n  <font color=YELLOW SIZE=12>Hydrolix<br>ACME CORP</FONT>\n  </center>"
   }
  },
  {
   "title": "Sales Volume",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 6, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(invoicedate) as time, count(*) as items_sold\nFROM hydrolix_demo_project.\"online_retail_transactions\" \nWHERE $__timeFilter(invoicedate)\nGROUP BY time ORDER BY time"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 }, "options": { "content": "Nice place for compression" } },
  {
   "title": "Total Period Revenue",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(price*quantity)\nFROM hydrolix_demo_project.\"online_retail_transactions\" \nWHERE   ( invoicedate  >= $__fromTime AND invoicedate <= $__toTime ) \n\n"
    }
   ]
  },
  {
   "title": "Total Sales By Country",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(price*quantity), country \nFROM hydrolix_demo_project.\"online_retail_transactions\" \nWHERE   ( invoicedate  >= $__fromTime AND invoicedate <= $__toTime ) \nGROUP BY country ORDER BY count() DESC"
    }
   ]
  },
  {
   "title": "Items Sold",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT  * FROM hydrolix_demo_project.\"online_retail_transactions\" \nWHERE $__timeFilter(invoicedate)\nORDER BY invoicedate\nLIMIT 500\n"
    }
   ]
  }
 ]
}